# Generated by Django 6.1 on 2026-10-05 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_post_content_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='spaces_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
