# Generated by Django 6.1 on 2026-10-06 18:58

import core_app.models.warranty
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_lead_spaces_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document', models.FileField(help_text='PDF de hasta 5 MB. Los documentos publicados son públicos.', upload_to=core_app.models.warranty.warranty_upload_path, validators=[core_app.models.warranty.validate_warranty_pdf], verbose_name='Documento PDF')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Documento de garantía',
                'verbose_name_plural': 'Documentos de garantía',
                'ordering': ('order', 'title', 'pk'),
            },
        ),
    ]
